version: '3.8'

services:
  pgAdmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: vladislav_petrovec@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"

  pgSQL:
    container_name: pg_sql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
